[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
StudentIdentityVerification = '0x5cbfd3a6a5ec5c0d9bc275b4a1bf1547a72119ca5990bf40b499bedfe0b8e7c0'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
